### ISSUE TITLE
Are you planning to release the code?

### ISSUE THREAD

**Issue by ninjasaid2k** [exx8/differential-diffusion#1]

**Comment by exx8** [comment]
Thank you for expressing your interest in our project. We are pleased to inform you that the code will soon be made available to the public. Please stay tuned for the upcoming release, and we appreciate your patience and support!

**Comment by TruthSearcher** [comment]
has the code been released yet?

**Comment by exx8** [comment]
Hello @TruthSearcher,
I appreciate you taking an interest in my project. I'm delighted you appreciate the early draft version of the article!
I value your interest in viewing the code and am grateful for your patience.
I'm pleased to inform you that the code will be included in the first official release of the paper, which will also have many additional improvements.
It is encouraging to learn about your interests, so thank you.
As soon as it becomes accessible, I'll be sure to let you know. Please feel free to contact me if you have any queries regarding the project in the interim.
Thanks!

**Comment by olliacc** [comment]
is this repo dead?

**Comment by exx8** [comment]
The repo is still alive!
I'm sorry for the waiting, I'm working hard to make sure the first official release will be as good it can be. Our team is a bit smaller than the usual number of authors for regular ML paper (we are only two)
So what is planned?
1. A new manuscript with new applications
2. Support for other diffusion models such as XL, Kandinsky, DeepFlyod IF.
3. Colab notebook
4. The paper's new website is now online:
https://differential-diffusion.github.io/

Thank you for your patience, I'm excited that you are interested in the paper!

**Comment by Lalimec** [comment]
any time soon?

**Comment by exx8** [comment]
The release is expected to be this Thursday!

**Comment by Lalimec** [comment]
> The release is expected to be on this Thursday!

haha didnt expected it to be this sooner, good luck!

**Comment by exx8** [comment]
> > The release is expected to be on this Thursday!
> 
> haha didnt expected it to be this sooner, good luck!

Sorry it took so long.

**Comment by exx8** [comment]
Well, Thursday has come early this week.
The code has been released!

**Comment by exx8** [comment]
Thank you for your patience!
