### ISSUE TITLE
Is it possible to clone the project and use it alone?

### ISSUE THREAD

**Issue by ifredom** [exx8/differential-diffusion#10]
Is it possible to clone the project and use it alone?

**Comment by exx8** [comment]
Yes of course, it's completely open. Once you clone the repo, you can follow those instructions:
https://github.com/exx8/differential-diffusion?tab=readme-ov-file#installation
Thanks for your interests in diff diff!

**Comment by exx8** [comment]
OK if you have any more questions, please feel free to re-open the issue or open another one.
I'm closing this for now.

Thanks
