### ISSUE TITLE
How to generate the map image effectively？ Are there any tools ？

### ISSUE THREAD

**Issue by zcfrank1st** [exx8/differential-diffusion#12]

**Comment by exx8** [comment]
Thanks for this question!
One can create change maps by:
1. Depth models, seems to be very effective for creating change maps. The depth map can be further tuned by histogram shifts and other simple transformation. For example, MiDas, Marigold.
2.  classical algorithms or by hand
3. Semantic segmentation such as: [lang-segment-anything](https://github.com/luca-medeiros/lang-segment-anything)

**Comment by exx8** [comment]
OK if you have any more questions, please feel free to re-open the issue or open another one.
I'm closing this for now.

Thanks
